ARG NODE_VERSION=10.15.3

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm ci

COPY . .

RUN ["npm", "run", "compile:dev"]

RUN ["npm", "link"]

CMD ["npm", "run", "node:version"]
