name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, e.g. v1.0, v20.15.10
      # Only a tag matching the filter patterns, here 'v*', can trigger the workflow.
      # See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build change list
        id: build_change_list
        shell: 'bash'
        # it works as there are only additions of new line, never any suppressions
        run: |
          CHANGES=$(git diff --minimal $(git tag --sort version:refname | grep ^v | tail -n 2 | head -n 1) $(git tag --sort version:refname | grep ^v | tail -n 1) CHANGELOG.md | sed -e '1,\|atao60/fse-cli/compare| d' -e '\|atao60/fse-cli/compare|,$ d' -e '1 d' -e 's/^\+//' | sed '1 i\# Changes about this release')
          CHANGES="${CHANGES//$'\n'/'%0A'}"
          CHANGES="${CHANGES//$'\r'/'%0D'}"
          echo CHANGES: "$CHANGES"
          echo "::set-output name=CHANGELIST::$CHANGES"
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Check change list
        id: check_change_list
        shell: 'bash'
        run: |
          echo CHANGELIST: "${{steps.build_change_list.outputs.CHANGELIST}}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "${{steps.build_change_list.outputs.CHANGELIST}}"
          draft: false
          prerelease: false
